name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update NPM
        run: sudo npm install -g npm@5

      - name: Run a postman test and generate reports
        run: |
          npm run dev:test

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: newman/
